### ISSUE TITLE
Add claude interface

### ISSUE THREAD

**Issue by doomspec** [doomspec/FibersOld#1]
### Motivation

We only have OpenAI interface now. We need one for claude

### Detailed Feature Description

See fibers/model/openai.py for the implementation of OpenAI interface.

**Comment by EigenSolver** [comment]
Hi Zijian, I think Claude is currently only available in North America. 

<img width="539" alt="Screenshot 2023-10-21 at 17 42 59" src="https://github.com/EvoEvolver/Fibers/assets/20223932/8fe6fbe8-7295-4490-adc4-d710b084fa39">

**Comment by doomspec** [comment]
gemini api added
